name:                shellsweeper
version:             0.1.0.0
github:              "brnzhg/shellsweeper"
license:             BSD3
author:              "Brian Zhang"
maintainer:          "brnzhg@gmail.com"
copyright:           "2018 Brian Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/brnzhg/shellsweeper#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- text
- random
- MonadRandom
- vector
- ansi-wl-pprint
- mtl
- exceptions
- lens
- optparse-applicative
- brick
- comonad
- adjunctions
- finite-typelits
- ghc-typelits-knownnat
- singletons
- linear
- vector-sized
- fgl
- hashable
- hashtables

library:
  source-dirs: src

executables:
  shellsweeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shellsweeper

tests:
  shellsweeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shellsweeper
